bool use_parameter_defaults
string device
int32 baudrate
int32 response_timeout_ms
string command
---
bool success
uint8 response_code
string message
uint8[] request_frame
uint8[] raw_frame
int32 code
