<?xml version="1.0"?>
<package format="3">
  <name>robot_embeded_bringup</name>
  <version>1.0.0</version>
  <description>Launch and configuration files for the robot embeded ROS2 framework.</description>
  <maintainer email="support@example.com">Robot Embeded Team</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>robot_embeded_interfaces</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_embeded_driver</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
